import { Task } from '@/types/task';
import { Employee } from '@/types/employee';
import { TaskMessage } from '@/types/message';
import { Notification } from '@/types/notification';

export const mockEmployees: Employee[] = [
    {
        id: 'emp-1',
        name: 'Ahmed Al-Mansoori',
        email: 'ahmed@alayam.com',
        role: 'Journalist',
        department: 'News',
        status: 'ACTIVE',
        availability: 'AVAILABLE',
        skills: ['interviews', 'breaking_news', 'politics'],
        performance_score: 98,
        response_time_avg: 180,
        total_tasks_completed: 142,
        created_at: '2024-01-15T08:00:00Z',
        last_active: '2026-02-17T00:30:00Z',
        avatar_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjiBGHYjscIDYf7W1JhWUatRpnn6v1HzEPpwuYRjbv2cMuRDontdLPt6QmCT92JamAfqr56pUlKrUTyThd_L5gDdnjO8iQIgiuJC20ZdFJRBkiDXSWCuhQEGdrQWcFYaPiYf5DsrplRinEvMbAXOCnkrJcjdAIzM31rMCB5mnoik9lmih6rUvYG9ojd3du4x1fQwGtvb_4VdjONqvnIIwFCYjnDTOT02x_20wvJnLpy5cfWXhSjBd61RxxHpK_h5Sa9c5TkAtH2pA',
    },
    {
        id: 'emp-2',
        name: 'Sarah Jenkins',
        email: 'sarah@alayam.com',
        role: 'Journalist',
        department: 'Business',
        status: 'ACTIVE',
        availability: 'BUSY',
        skills: ['economics', 'fact_checking', 'analysis'],
        performance_score: 92,
        response_time_avg: 240,
        total_tasks_completed: 98,
        created_at: '2024-03-10T08:00:00Z',
        last_active: '2026-02-16T22:15:00Z',
        avatar_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAPplEhByBWkC2LjpX9RlFNLVHwvVW6y3zxnF9yK1NPAJ-BPPws0CQCIxyD1eb75GSABm1PNcRJSsArdDBtN4VdZ4ri_sOXr4dtMI8BXixLMKW2AC19RaQHn458VCJf44DPKjrg2umjLynMk7zJ7aPiOtxTpIXDcI4SernaeiHF4rqYpunRRBl5pEeH3x3QZX-tDLczr4pVN05Xg3MSgDwQ5iwAoANeT8N75D1TlfBJwxkFrfRvYBZokrRLBozyuTx7SBlAGa2TNi8',
    },
    {
        id: 'emp-3',
        name: 'Khalid Omar',
        email: 'khalid@alayam.com',
        role: 'Photographer',
        department: 'News',
        status: 'ACTIVE',
        availability: 'AVAILABLE',
        skills: ['photography', 'arts_culture', 'events'],
        performance_score: 88,
        response_time_avg: 300,
        total_tasks_completed: 76,
        created_at: '2024-05-20T08:00:00Z',
        last_active: '2026-02-16T23:45:00Z',
        avatar_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD3R3e1U0bbYChf_fKvJcb7jQhvUAz6HWBwAlR868Wm51f1LLsanPYQfgERri-7KGxj6ZpwwT-E8KClmZvmD3K73stgqn3dIkzvINQmQ8_BTBxUwogmUlQLUnv28Zcedm8fNVDbMNwk70ojVOSJ93eFlG4-VjbLUlZh6GdPl2ZMEBhUXiDqXN8inkKVSA7vYYoPR0QJ-CbRnNDtZP3m2-rIHbTnXbOj8mvZCEX6SD0BmXTBS7P4gufBZgfUB4KUFViuxiP9bY5a63Q',
    },
    {
        id: 'emp-4',
        name: 'Omar Farooq',
        email: 'ofarooq@alayam.com',
        role: 'Journalist',
        department: 'Technology',
        status: 'ACTIVE',
        availability: 'BUSY',
        skills: ['technology', 'ai_coverage', 'conferences'],
        performance_score: 85,
        response_time_avg: 200,
        total_tasks_completed: 63,
        created_at: '2024-06-01T08:00:00Z',
        last_active: '2026-02-16T21:30:00Z',
        avatar_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA9W-iFM27qXkEzjUb5hzw-KDUp1aOHU4MqQCIDpeA_y4UNRuC9ayJCwPxfIY_SIgUf9yGSK3rFQfM6fxjRICFmT2l0umkdDJyS2ui_o78e6zbqv6niJ8HVs_9GoV322xSZwUiK8d6zjpH0_aWjol-CnVs3wFlrtASIENKc0YHjbQ7Ik9ZQS8AD5bo1g9CgO7YQqHJx66VLzh2xuD1dhgbxPrCu2I7c5qeq1rs6pJf192iB_yCR3KB_XlpSWfSBbH-oigzMz_hoiDQ',
    },
    {
        id: 'emp-5',
        name: 'Layla Mahmoud',
        email: 'layla@alayam.com',
        role: 'Journalist',
        department: 'Politics',
        status: 'ACTIVE',
        availability: 'AVAILABLE',
        skills: ['politics', 'investigations', 'crime'],
        performance_score: 92,
        response_time_avg: 150,
        total_tasks_completed: 110,
        created_at: '2024-02-01T08:00:00Z',
        last_active: '2026-02-17T00:10:00Z',
        avatar_url: '',
    },
    {
        id: 'emp-6',
        name: 'Karim Nabil',
        email: 'karim@alayam.com',
        role: 'Photographer',
        department: 'Sports',
        status: 'ACTIVE',
        availability: 'OFF_DUTY',
        skills: ['sports', 'photography', 'video'],
        performance_score: 85,
        response_time_avg: 400,
        total_tasks_completed: 55,
        created_at: '2024-07-15T08:00:00Z',
        last_active: '2026-02-16T18:00:00Z',
        avatar_url: '',
    },
];

export const mockTasks: Task[] = [
    {
        id: 'tsk-001',
        title: 'Breaking: Emergency landing at Bahrain Airport',
        description: 'Initial reports indicate technical failure. Emergency crews dispatched. Require live feed setup asap.',
        type: 'BREAKING_NEWS',
        priority: 'URGENT',
        status: 'IN_PROGRESS',
        assignee_id: 'emp-1',
        creator_id: 'mgr-1',
        deadline: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
        estimated_duration: 60,
        deliverables: { photos: 5, quotes: 3 },
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        sent_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        accepted_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
        started_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        response_time: 1800,
        escalation_count: 0,
    },
    {
        id: 'tsk-002',
        title: 'Review: Annual Economic Report Draft',
        description: 'Fact check the inflation statistics for Q3. Cross reference with central bank data.',
        type: 'FACT_CHECK',
        priority: 'HIGH',
        status: 'SENT',
        assignee_id: 'emp-2',
        creator_id: 'mgr-1',
        deadline: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
        estimated_duration: 180,
        created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        sent_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        escalation_count: 0,
    },
    {
        id: 'tsk-003',
        title: 'Interview: Local Artist Exhibition',
        description: 'Conduct interview with Fatima Al-Sayed about her upcoming gallery opening in Manama.',
        type: 'INTERVIEW',
        priority: 'NORMAL',
        status: 'IN_PROGRESS',
        assignee_id: 'emp-3',
        creator_id: 'mgr-1',
        deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
        estimated_duration: 120,
        deliverables: { photos: 10, quotes: 5 },
        created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        sent_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        accepted_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        started_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        response_time: 3600,
        escalation_count: 0,
    },
    {
        id: 'tsk-004',
        title: 'Viral: Tech Conference Keynote',
        description: 'Summarize the keynote speech from GITEX. Focus on AI regulations mentioned by the minister.',
        type: 'PRESS_CONF',
        priority: 'URGENT',
        status: 'REVIEW',
        assignee_id: 'emp-4',
        creator_id: 'mgr-1',
        deadline: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
        estimated_duration: 90,
        deliverables: { quotes: 5 },
        created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        sent_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        accepted_at: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
        started_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        completed_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        response_time: 1800,
        completion_time: 12600,
        escalation_count: 0,
    },
    {
        id: 'tsk-005',
        title: 'Follow-Up: Water Crisis Investigation',
        description: 'Follow up on the rural communities water supply issue. Check for government response.',
        type: 'FOLLOW_UP',
        priority: 'HIGH',
        status: 'ACCEPTED',
        assignee_id: 'emp-5',
        creator_id: 'mgr-1',
        deadline: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
        estimated_duration: 240,
        created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        sent_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        accepted_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        response_time: 900,
        escalation_count: 0,
    },
    {
        id: 'tsk-006',
        title: 'Photo Coverage: National Day Ceremony',
        description: 'Capture photos at the National Day ceremony downtown. Focus on dignitaries and celebrations.',
        type: 'PHOTO_ASSIGN',
        priority: 'NORMAL',
        status: 'DRAFT',
        creator_id: 'mgr-1',
        deadline: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
        estimated_duration: 180,
        deliverables: { photos: 20, video: 1 },
        created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
        escalation_count: 0,
    },
];

export const mockMessages: TaskMessage[] = [
    {
        id: 'msg-1',
        task_id: 'tsk-001',
        sender_id: 'emp-2',
        sender_name: 'Sarah Jenkins',
        message_type: 'TEXT',
        content: "Just arrived at the scene. It's pretty chaotic. 🚨",
        direction: 'INBOUND',
        status: 'READ',
        sent_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        is_system_message: false,
    },
    {
        id: 'msg-2',
        task_id: 'tsk-001',
        sender_id: 'mgr-1',
        sender_name: 'Editor',
        message_type: 'TEXT',
        content: 'Stay safe. Send us the raw footage as soon as you can. We are going live in 20.',
        direction: 'OUTBOUND',
        status: 'READ',
        sent_at: new Date(Date.now() - 44 * 60 * 1000).toISOString(),
        is_system_message: false,
    },
    {
        id: 'msg-3',
        task_id: 'tsk-001',
        sender_id: 'emp-2',
        sender_name: 'Sarah Jenkins',
        message_type: 'IMAGE',
        content: 'First look at the terminal entrance.',
        media_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBIT-5gAlwVjwE3QG2ItHOLUBcOREvUpxf3w2ir4slnCAQxmaAbUkMvg4t5EloE1P90saECpe-VYPQTagr0dIe26HlwP7f76JcloZ7n51B5Jip553z4uYjvCjkhhKawuxqDksOOscRz-QdKNwobAw6xXcpsifyL_4-7BfDJLC4e1ScheUNVY7Z78BW-essY3Ne8i7_22h-5EX-kZShaLuwkrss5ebnUOZxq_sYvFL4LW-0AJ1Q_VOxXVA5fS-9sx8F2otW3obUYkMM',
        media_type: 'image/jpeg',
        direction: 'INBOUND',
        status: 'READ',
        sent_at: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
        is_system_message: false,
    },
    {
        id: 'msg-4',
        task_id: 'tsk-001',
        sender_id: 'emp-1',
        sender_name: 'Ahmed Al-Mansoori',
        message_type: 'AUDIO',
        content: '',
        direction: 'INBOUND',
        status: 'DELIVERED',
        sent_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
        is_system_message: false,
    },
];

export const mockNotifications: Notification[] = [
    {
        id: 'notif-1',
        recipient_id: 'mgr-1',
        type: 'TASK_ACCEPTED',
        priority: 'HIGH',
        title: 'Task Accepted',
        message: 'Ahmed Al-Mansoori accepted "Breaking: Emergency Landing"',
        task_id: 'tsk-001',
        status: 'READ',
        created_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'notif-2',
        recipient_id: 'mgr-1',
        type: 'MEDIA_UPLOADED',
        priority: 'NORMAL',
        title: 'New Media Uploaded',
        message: 'Sarah Jenkins uploaded 3 photos for "Emergency Landing"',
        task_id: 'tsk-001',
        status: 'DELIVERED',
        created_at: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    },
    {
        id: 'notif-3',
        recipient_id: 'mgr-1',
        type: 'TASK_COMPLETED',
        priority: 'NORMAL',
        title: 'Task Ready for Review',
        message: 'Omar Farooq submitted "Tech Conference Keynote" for review',
        task_id: 'tsk-004',
        status: 'PENDING',
        created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    {
        id: 'notif-4',
        recipient_id: 'mgr-1',
        type: 'DEADLINE_APPROACHING',
        priority: 'CRITICAL',
        title: 'Deadline Approaching',
        message: '"Emergency Landing" deadline in 30 minutes',
        task_id: 'tsk-001',
        status: 'PENDING',
        created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    },
];
